version: "3.8"

services:
###Iniciar página: http://localhost:8880/otrs/index.pl 
###Usuário: root@localhost
###Senha: cXldfmKMtLAT4FGD
  otrs:
    image: alderpinto/otrs-ce:6.0.18
    restart: always
    ports:
#      - 443:443
      - 9980:8880
      - 9981:8881
    env_file: .env      
    volumes:
#      - ./letsencrypt:/etc/letsencrypt
#      - ./Config.pm:/opt/otrs/Kernel/Config.pm
      - ./init:/app
      - ./app:/opt/otrs
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mjeffomybyov7xffcba6
    command:
      - --max-allowed-packet=64M
      - --innodb-buffer-pool-size=256M
      - --innodb-log-file-size=128M
      - --character-set-server=utf8
      - --bind-address=0.0.0.0      
###  postgres:
######Usuário: otrs
######Senha: G9MB0dCQ72wlnHpu  
###    image: postgres:15
###    container_name: postgres
###    restart: always
###    environment:
###      POSTGRES_USER: root
###      POSTGRES_PASSWORD: mjeffomybyov7xffcba6
###      PGDATA: "/var/lib/postgresql/data/pgdata"
###    volumes:
###      - postgres:/var/lib/postgresql/data

#volumes:
#  postgres: